name: noventa_oito
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.13
  http: ^1.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - fake_drivers/
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/montserrat.ttf
        - asset: fonts/montserrat_light.ttf
        - asset: fonts/montserrat_bold.ttf
